apiVersion: apps/v1
kind: Deployment
metadata:
  name: filter-selector-nautic
  labels:
    app: filter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: filter
  template:
    metadata:
      labels:
        app: filter
    spec:
      containers:
      - name: api
        image: aldresdev/filter_selector:v1
        env:
          - name: CENTRAL_HOST
            value: "192.168.1.21"
          - name: CENTRAL_PORT
            value: "8000"
          - name: SERVER_HOST
            value: "192.168.1.21"
          - name: FRAME_PORT
            value: "30004"
          - name: REQUEST_PORT
            value: "30005"
        ports:
          - containerPort: 30004
---

apiVersion: v1
kind: Service
metadata:
  name: filter-service1
spec:
  type: NodePort
  selector:
    app: filter
  ports:
    - port: 80
      targetPort: 30004
      nodePort: 30004
