apiVersion: apps/v1
kind: Deployment
metadata:
  name: galaxy-tracker-nautic
  labels:
    app: galaxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: galaxy
  template:
    metadata:
      labels:
        app: galaxy
    spec:
      containers:
      - name: api
        image: aldresdev/galaxy_tracker:v1
        env:
          - name: CENTRAL_HOST
            value: "192.168.1.21"
          - name: CENTRAL_PORT
            value: "8000"
          - name: SERVER_HOST
            value: "192.168.1.21"
          - name: FRAME_PORT
            value: "30010"
        ports:
          - containerPort: 30010
---

apiVersion: v1
kind: Service
metadata:
  name: galaxy-service1
spec:
  type: NodePort
  selector:
    app: galaxy
  ports:
    - port: 80
      targetPort: 30010
      nodePort: 30010
