apiVersion: apps/v1
kind: Deployment
metadata:
  name: video-capturer-nautic
  labels:
    app: capturer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: capturer
  template:
    metadata:
      labels:
        app: capturer
    spec:
      containers:
      - name: api
        volumeMounts:
        - mountPath: /dev/video0
          name: dev-video0
        securityContext:
          privileged: true
        image: aldresdev/video_capturer:v1
        env:
          - name: CENTRAL_HOST
            value: "192.168.1.21"
          - name: CENTRAL_PORT
            value: "8000"
      volumes:
      - name: dev-video0
        hostPath:
          path: /dev/video0
